ci: Fix and re-enable strict shasum check

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -93,29 +93,27 @@ jobs:
           ls -la dist >&2
 
           # Verify total files and shasum of `pack` and `publish` are the same
-          pack_sout=$(npm pack --dry-run 2>&1)
+          pack_filename=$(pnpm pack | tail -n1)
           publish_sout=$(pnpm publish --access public --no-git-checks --dry-run 2>&1)
 
-          printf "\e[1mnpm pack (dry run):\e[m\n" >&2
-          printf "$pack_sout\n\n\n" >&2
           printf "\e[1mnpm publish (dry run):\e[m\n" >&2
           printf "$publish_sout\n\n\n" >&2
 
-          pack_shasum=$(<<< "$pack_sout" command sed '/shasum/!d; s/.*:\s*\(.*\)$/\1/')
+          pack_shasum=$(shasum -b -a 1 "${pack_filename}" | awk '{ print $1 }')
           publish_shasum=$(<<< "$publish_sout" command sed '/shasum/!d; s/.*:\s*\(.*\)$/\1/')
 
-          pack_total_files=$(<<< "$pack_sout" command sed '/total.files/!d; s/.*:\s*\(.*\)$/\1/')
+          pack_total_files=$(tar -tvf "${pack_filename}" | wc -l)
           publish_total_files=$(<<< "$publish_sout" command sed '/total.files/!d; s/.*:\s*\(.*\)$/\1/')
 
           has_error=
           if [[ "$pack_shasum" != "$publish_shasum" ]]; then
-            printf "\e[1;38;5;208mWarning:\e[m Package shasum do not match:\n" >&2
+            printf "\e[1;31mError:\e[m Package shasum do not match:\n" >&2
             printf "  npm pack    shasum: $pack_shasum\n" >&2
             printf "  npm publish shasum: $publish_shasum\n" >&2
             has_error=1
           fi
 
-          if [[ "$pack_total_files" != "$publish_total_files" ]]; then
+          if (( pack_total_files != publish_total_files )); then
             printf "\e[1;31mError:\e[m Package total files do not match:\n" >&2
             printf "  npm pack    total files: $pack_total_files\n" >&2
             printf "  npm publish total files: $publish_total_files\n" >&2
@@ -123,13 +121,19 @@ jobs:
           fi
 
           if [[ -n "$has_error" ]]; then
-            printf "Aborting due to previous errors.\n" >&2
+            printf "\e[1;38;5;208mWarning:\e[m Aborting due to previous errors.\n" >&2
+
             # Revert tag
+            printf "\e[1;38;5;208mWarning:\e[m Unpublishing release tag ${{ steps.new-version.outputs.new_tag }}.\n" >&2
             git tag -d "${{ steps.new-version.outputs.new_tag }}"
             git push --delete origin "${{ steps.new-version.outputs.new_tag }}"
+
             # Revert commit
+            printf "\e[1;38;5;208mWarning:\e[m Unpublishing release commit.\n" >&2
             git reset --hard HEAD^
             git push origin --force-with-lease
+
+            printf "\e[1;38;5;208mWarning:\e[m Clean up done.\n" >&2
             exit 1
           fi
 
